### ISSUE TITLE
nextjs-node-loader _workingDri/.next/server/chunks/{FILENAME}.node not found

### ISSUE THREAD

**Issue by 200sOnly** [eisberg-labs/nextjs-node-loader#29]
Firstly, thanks for creating this package. It's much needed for our project.

After installing your plugin I can successfully run the project locally and be able to build it.
But when I deployed it, the API route endpoint failed complaining the .node file was missing even though when I downloaded the artifact I could see it right there.

When I downloaded the artifact and read the minified `route.js` minified file, I see following code:
```
try {
    process.dlopen(e, "/working_dir/.next/server/chunks" + r(71017).sep + "ccauth.node", 2)
} catch (e) {
    throw Error("nextjs-node-loader:\n" + e)
}
}
```

I'm suspecting it fails at the above try catch as this matches with the error I see

I have ```output: "standalone",``` in next.config.js

Following is my configuration:
```
    webpack: (config, { dev, isServer, webpack, nextRuntime }) => {
        config.module.rules.push({
            test: /\.node$/,
            use: [
                {
                    loader: "nextjs-node-loader",
                    options: {
                        flags: os.constants.dlopen.RTLD_NOW,
                        outputPath: config.output.path
                    }
                },
            ],
        });
        return config;
    },
```

Next: 14x
Deploying to Azure Static Web App using Oryx

If you can think of any new debugging ideas or workarounds, please suggest.

**Comment by amarjanica** [comment]
Hi sorry for being late, just saw your issue. I'll need more info:
- you're using the [v1.1.5-alpha.0](https://github.com/eisberg-labs/nextjs-node-loader/releases/tag/v1.1.5-alpha.0)? This sounds like an issue that's fixed in that version. If that's the case I'll promote it to stable.
- if I get this, you can run it on dev, the project builds. If you run the production build locally, it works? `npm run build & npm run start`.
